### ISSUE TITLE
Translation API not available without a backend server

### ISSUE THREAD

**Issue by jeffeuxMartin** [lopentu/nlp_web#2]
如題，這個「挑戰題」中「翻譯」的難度也未免太難了～
想請教各位有沒有繞過去的解法 🥲

![image](https://user-images.githubusercontent.com/43311603/196005680-2c5fa940-b547-4ea4-9cd8-02f4725fd52c.png)

這個 API 我千方百計嘗試都沒有辦法使用，
看到 `require` 關鍵字就猜這大概是 Node.js 後端的 API
單純像使用 JiebaJS 那樣用前端匯入其他人的 script 好像很難做到
查詢其他類似的 API 也都是後端 API，前端的 Google API 一來要 project ID 二來好像要錢
想請教老師、助教或各位同學有沒有其他更好的方法可以解決？ 😰 
（搞掉大約 5 小時，還是用一個很繞很複雜的方法才勉強繞過去
　以下是第一個版本： https://jeffeuxmartin.github.io/advanced-school-song/ntu.html ）

**Comment by Retr0327** [comment]
Hi @jeffeuxMartin , 
雖然我不是助教，只是幫忙謝老師寫小小的 assignment 作業的學員，但偶爾客串回文，debug 我們的人生

我剛剛看了一下 npm trends：

![trend](https://user-images.githubusercontent.com/48786838/196054018-3a35c10e-d408-4698-9ede-f3bb0f9326be.png)

不難看出 `google-translate-api` 已經逐漸被捨棄，現在主流都是使用 [@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api)

[@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api) 在使用上就不會有  `BAD_REQUEST` 的 error message：

```typescript
import translate from "google-translate-api"

translate('我說英語', { to: 'en'}).then(res => {
  console.log(res);
}).catch(err => {
  console.error(err);
});
```

所得到的 output：

```typescript
{
  text: 'I speak English',
  pronunciation: null,
  from: {
    language: { didYouMean: false, iso: 'zh-TW' },
    text: { autoCorrected: false, value: '', didYouMean: false }
  },
  raw: [
    [ 'Wǒ shuō yīngyǔ', null, 'zh-TW', [Array], [Array] ],
    [ [Array], 'en', 1, 'zh-TW', [Array] ],
    'zh-TW'
  ]
}
```
成功 fetch！接下來就可以去把玩裡面的各種 fields～
希望有幫到你～！

**Comment by Retr0327** [comment]
Hi @jeffeuxMartin , 
雖然我不是助教，只是幫忙謝老師寫小小的 assignment 作業的學員，但偶爾客串回文，debug 我們的人生

我剛剛看了一下 npm trends：

![trend](https://user-images.githubusercontent.com/48786838/196054018-3a35c10e-d408-4698-9ede-f3bb0f9326be.png)

不難看出 `google-translate-api` 已經逐漸被捨棄，現在主流都是使用 [@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api)

[@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api) 在使用上就不會有  `BAD_REQUEST` 的 error message：

```typescript
import translate from "google-translate-api"

translate('我說英語', { to: 'en'}).then(res => {
  console.log(res);
}).catch(err => {
  console.error(err);
});
```

所得到的 output：

```typescript
{
  text: 'I speak English',
  pronunciation: null,
  from: {
    language: { didYouMean: false, iso: 'zh-TW' },
    text: { autoCorrected: false, value: '', didYouMean: false }
  },
  raw: [
    [ 'Wǒ shuō yīngyǔ', null, 'zh-TW', [Array], [Array] ],
    [ [Array], 'en', 1, 'zh-TW', [Array] ],
    'zh-TW'
  ]
}
```
成功 fetch！接下來就可以去把玩裡面的各種 fields～
希望有幫到你～！

**Comment by Retr0327** [comment]
> 如題，這個「挑戰題」中「翻譯」的難度也未免太難了～ 想請教各位有沒有繞過去的解法 🥲
> 
> ![image](https://user-images.githubusercontent.com/43311603/196005680-2c5fa940-b547-4ea4-9cd8-02f4725fd52c.png)
> 
> 這個 API 我千方百計嘗試都沒有辦法使用， 看到 `require` 關鍵字就猜這大概是 Node.js 後端的 API 單純像使用 JiebaJS 那樣用前端匯入其他人的 script 好像很難做到 查詢其他類似的 API 也都是後端 API，前端的 Google API 一來要 project ID 二來好像要錢 想請教老師、助教或各位同學有沒有其他更好的方法可以解決？ 😰 （搞掉大約 5 小時，還是用一個很繞很複雜的方法才勉強繞過去 　以下是第一個版本： https://jeffeuxmartin.github.io/advanced-school-song/ntu.html ）

Hi @jeffeuxMartin , 
雖然我不是助教，只是幫忙謝老師寫小小的 assignment 作業的學員，但偶爾客串回文，debug 我們的人生

我剛剛看了一下 npm trends：

![trend](https://user-images.githubusercontent.com/48786838/196054018-3a35c10e-d408-4698-9ede-f3bb0f9326be.png)

不難看出 `google-translate-api` 已經逐漸被捨棄，現在主流都是使用 [@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api)

[@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api) 在使用上就不會有  `BAD_REQUEST` 的 error message：

```typescript
import translate from "google-translate-api"

translate('我說英語', { to: 'en'}).then(res => {
  console.log(res);
}).catch(err => {
  console.error(err);
});
```

所得到的 output：

```typescript
{
  text: 'I speak English',
  pronunciation: null,
  from: {
    language: { didYouMean: false, iso: 'zh-TW' },
    text: { autoCorrected: false, value: '', didYouMean: false }
  },
  raw: [
    [ 'Wǒ shuō yīngyǔ', null, 'zh-TW', [Array], [Array] ],
    [ [Array], 'en', 1, 'zh-TW', [Array] ],
    'zh-TW'
  ]
}
```
成功 fetch！接下來就可以去把玩裡面的各種 fields～
希望有幫到你～！

**Comment by Retr0327** [comment]
Hi @jeffeuxMartin , 
雖然我不是助教，只是幫忙謝老師寫小小的 assignment 作業的學員，但偶爾客串回文，debug 我們的人生

我剛剛看了一下 npm trends：

![trend](https://user-images.githubusercontent.com/48786838/196054018-3a35c10e-d408-4698-9ede-f3bb0f9326be.png)

不難看出 `google-translate-api` 已經逐漸被捨棄，現在主流都是使用 [@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api)

[@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api) 在使用上就不會有  `BAD_REQUEST` 的 error message：

```typescript
import translate from "google-translate-api"

translate('我說英語', { to: 'en'}).then(res => {
  console.log(res);
}).catch(err => {
  console.error(err);
});
```

所得到的 output：

```typescript
{
  text: 'I speak English',
  pronunciation: null,
  from: {
    language: { didYouMean: false, iso: 'zh-TW' },
    text: { autoCorrected: false, value: '', didYouMean: false }
  },
  raw: [
    [ 'Wǒ shuō yīngyǔ', null, 'zh-TW', [Array], [Array] ],
    [ [Array], 'en', 1, 'zh-TW', [Array] ],
    'zh-TW'
  ]
}
```
成功 fetch！接下來就可以去把玩裡面的各種 fields～
希望有幫到你～！

**Comment by jeffeuxMartin** [comment]
@Retr0327 哈囉您好，
感謝您的回覆，哈哈不瞞您說（抱歉 code 偏醜，畢竟只是想先動起來而已）
<img width="593" alt="image" src="https://user-images.githubusercontent.com/43311603/196056683-7aa3dbc8-eb40-4bc8-9c95-c378349a4fdf.png">
我確實是用那一個 npm 套件的！然而我這邊測試原本的 google-translate-api 也是可以運作的，但沒有這個今年出的新版本穩定就是～
我現在的方法就是先用 Heroku 架一個後端把這個服務丟上去，然後再用前端去 request 它沒錯
但我在此想問老師的是有沒有可能跟 JiebaJS 一樣有一個雲端 cdn 庫可以直接用 :-D 
沒有也沒關係，可是這個作業就變爆炸難了 T_T （後端開發應該超出本學期課程內容了？）

還是非常感謝您的指點 :-) 往後還請多多指教～

喔喔不過如果那是純前端就可以做到的，那我有空再試試，這方面還得向您多多學習了 <(_ _)>

**Comment by Retr0327** [comment]
Hi @jeffeuxMartin ,

原來如此，我能想到最簡單的方式就是像你一樣架設一個小 api-gateway 去處理它～
如果是單純用 plain html 的話好像就很麻煩（向所有前端工程師致敬），要馬是用 cdn 或是用 bundle 的方式，我剛剛試了一下 [@vitalets/google-translate-api](https://www.npmjs.com/package/@vitalets/google-translate-api) 的 bundle（我用簡便的 browserify），似乎也不太行，可能試試 babel 或 webpack 有機會

但如果之後用 React 做 github pages 的話應該就簡單多了

拍謝沒啥幫上忙，但一起討論總是有所收穫～

**Comment by jeffeuxMartin** [comment]
對了，後來助教有給予一個 Rapid API 的處理方式
但那會有一個問題是 API key 會被暴露在部署後的網頁原始碼中，造成 quota 疑慮

再後來感謝一位修課的同學讓我知道有這樣一個好網站可以使用
這邊似乎就沒有 API key 的問題了，供大家參考
```javascript
const free_translator = async ({
  text,
  source_language = "en",
  target_language = "de",
}) => {
  return await fetch(
    "https://libretranslate.de/translate?" +
      new URLSearchParams({
        q: text,
        source: source_language,
        target: target_language,
      }).toString(),
    { method: "POST" })
    .then((resp) => new Response(resp.body).json())
    .then((json) => json["translatedText"]);
};
```
